apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.scheme }}
    alb.ingress.kubernetes.io/tags: scos.delete.on.teardown=true
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-path: /health_check.php
    alb.ingress.kubernetes.io/subnets: {{ .Values.ingress.subnets }}
    alb.ingress.kubernetes.io/security-groups: {{ .Values.ingress.security_groups }}
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.certificate_arns }}
    alb.ingress.kubernetes.io/actions.redirect: '{"Type": "redirect", "RedirectConfig":{"Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/actions.redirect-to-datajson: '{"Type": "redirect", "RedirectConfig":{"Protocol": "HTTPS", "Port": "443", "Host": "data.{{ .Values.ingress.root_dns_zone }}", "Path": "/api/v1/data_json", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
spec:
  backend:
    serviceName: {{ .Values.service.name }}
    servicePort: {{ .Values.service.port }}
  rules:
  - host: www.{{ .Values.ingress.root_dns_zone }}
    http:
      paths:
      - path: /data.json
        backend:
          serviceName: redirect-to-datajson
          servicePort: use-annotation
      - path: /*
        backend:
          serviceName: redirect
          servicePort: use-annotation