kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "scos-joomla.fullname" . }}-storage
  labels:
    component: joomla
spec:
  storageClassName: standard-ssd
  accessModes:
  - {{ .Values.storage.mode }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}